### ISSUE TITLE
Null-safety issue.

### ISSUE THREAD

**Issue by creky** [Arbaz-Softagics/commons#13]
I had upgrade this project to null-safety support. But I had modified the ui of the dialogs. If you don't mind it, you can use :
```
commons:
    git:
      url: 'https://github.com/Creky/commons.git'
      ref: master
```
